[package]
name = "sui_quest"
edition = "2024.beta"  # Use "2024.beta" for modern Move features. Use "legacy" for pre-2024 syntax.
version = "0.0.1"
published-at = "0x79819cfbf000b4cb1599e5c289216336b02f412b1e6e330e080830e6aec3166e"
license = "MIT"
authors = ["Emmanuel Chidi <chidiemmanuel2005@gmail.com>"]  # Replace with actual name/email or remove if private
publish = "compatible"

[dependencies]
# Add dependencies here if your package imports from other Move modules
# Example:
# sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "main" }

[addresses]
sui_quest = "0x0"  # Use "0x0" as placeholder for development, will be replaced during publish

[dev-dependencies]
# Add dev-only modules for testing if needed
# Example:
# test_helpers = { local = "../test_helpers" }

[dev-addresses]
# Used for tests or `--dev` mode with address overrides
# Example:
# alice = "0xB0B"

